config/routes.rb
Rails.application.routes.draw do
  resources :addposts
  get 'password_resets/new'

  get 'passwrod_resets/new'

  get 'passwrod_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts

  resources :users
  get '/singup', to: 'users#new'
  post '/singup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :contacts, only: [:new, :show, :create]
end

app/models/addpost.rb
class Addpost < ApplicationRecord

  validates :title, presence: true, length: {minimum: 3 }
  validates :body, presence: true, length: {minimum: 3 }

end

app/controllers/addposts_controller.rb
class AddpostsController < ApplicationController
  before_action :set_addpost, only: [:show, :edit, :update, :destroy]
  before_action :logged_in_user, only: [:index, :destroy]

  # GET /addposts
  # GET /addposts.json
  def index
    @addposts = Addpost.all
  end

  # GET /addposts/1
  # GET /addposts/1.json
  def show
  end

  # GET /addposts/new
  def new
    @addpost = Addpost.new
  end

  # GET /addposts/1/edit
  def edit
  end

  # POST /addposts
  # POST /addposts.json
  def create
    @addpost = Addpost.new(addpost_params)

    respond_to do |format|
      if @addpost.save
        format.html { redirect_to @addpost, notice: 'Addpost was successfully created.' }
        format.json { render :show, status: :created, location: @addpost }
      else
        format.html { render :new }
        format.json { render json: @addpost.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /addposts/1
  # PATCH/PUT /addposts/1.json


  # DELETE /addposts/1
  # DELETE /addposts/1.json
  def destroy
    @addpost.destroy
    respond_to do |format|
      format.html { redirect_to addposts_url, notice: 'Addpost was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_addpost
      @addpost = Addpost.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def addpost_params
      params.require(:addpost).permit(:title, :body, :text)
    end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:info] = "Please log in"
      redirect_to login_url
    end
  end
end

app/helpers/addposts_helper.rb
module AddpostsHelper
end

app/views/addposts/_form.html.erb
<div class="col-md-6 col-offset-3">
<%= form_with(model: addpost, local: true) do |form| %>
  <% if addpost.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(addpost.errors.count, "error") %> prohibited this addpost from being saved:</h2>

      <ul>
      <% addpost.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, id: :addpost_title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_field :body, id: :addpost_body, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :text %>
    <%= form.text_field :text, id: :addpost_text, class: 'form-control' %>
  </div>

  <div class="actions">
    <%= form.submit 'Offer post', class: 'btn btn-pimary' %>
  </div>
<% end %>
</div>

app/views/addposts/edit.html.erb
<h1>Editing Addpost</h1>

<%= render 'form', addpost: @addpost %>

<%= link_to 'Show', @addpost %> |
<%= link_to 'Back', addposts_path %>

app/views/addposts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Addposts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th>Text</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @addposts.each do |addpost| %>
      <tr>
        <td><%= addpost.title %></td>
        <td><%= addpost.body %></td>
        <td><%= addpost.text %></td>
        <td><%= link_to 'Show', addpost %></td>
        <td><%= link_to 'Edit', edit_addpost_path(addpost) %></td>
        <td><%= link_to 'Destroy', addpost, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Addpost', new_addpost_path %>

app/views/addposts/new.html.erb
<%= render 'shared/miniheader' %>
<h1>New Addpost</h1>

<%= render 'form', addpost: @addpost %>

app/views/addposts/show.html.erb
<%= render 'shared/miniheader' %>
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @addpost.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @addpost.body %>
</p>

<p>
  <strong>Text:</strong>
  <%= @addpost.text %>
</p>

<%= link_to 'Edit', edit_addpost_path(@addpost) %> |
<%= link_to 'Back', addposts_path %>