config/routes.rb
Rails.application.routes.draw do
  resources :addposts
  get 'password_resets/new'

  get 'passwrod_resets/new'

  get 'passwrod_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts

  resources :users
  get '/singup', to: 'users#new'
  post '/singup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :contacts, only: [:new, :show, :create]
end

app/models/post.rb
class Post < ApplicationRecord
  mount_uploader :image, ImageUploader
  default_scope -> {order(created_at: :desc)}
  validates :title, :body, presence: true


end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :logged_in_user, only: [:create, :new, :edit, :destroy, :update]


  before_action :search_post, only: [:show, :edit, :update, :destroy]

  def index
    @posts = Post.paginate(page: params[:page])
  end

  def show

  end

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    if admin
    @post.save
      redirect_to @post, success: 'Your create new post'
    else
      render :new, warning: 'Opps we have got some problems'
    end
  end

  def edit

  end

  def update
    if  admin
    @post.update_attributes(post_params)
      redirect_to @post, success: 'ALL OK, your update post '
    else
      render :edit, warning: 'Opps we have got some problems'
    end
  end

  def destroy
    if admin
    @post.destroy
    redirect_to post_path
    else
      redirect_to root_url
      flash.now[:info] = "You adre not admin"
      end
  end




  private

  def post_params
      params.require(:post).permit(:title, :body, :image)
  end

  def search_post
    @post = Post.find(params[:id])
  end

  def logged_in_user
    unless logged_in?
      store_location
      flash[:info] = "Please log in"
      redirect_to login_url
    end
  end

  def admin
    redirect_to(root_url) unless current.user.admin?
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<% if @post.errors.any? %>
   <div class="alert alert-danger">
     <h5><%= t('common.errors') %></h5>
     <ul>
       <% @post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
       <%end %>
     </ul>
   </div>
    <% end %>


<%= form_for @post, html: {multipart: true} do |f| %>
<div class="form-group">
<%= f.label :title %>
<%=f.text_field :title, class: 'form-control'%>
</div>


    <div class="form-group">
<%= f.label :body%>
<%= f.text_area :body, class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= f.file_field :image %>
    </div>


<%=f.submit  class: 'btn btn-primary'%>
<% end %>

app/views/posts/edit.html.erb
<h2>EDIT FORM PANEL</h2>

<%= render 'form' %>
<%= link_to 'Delete post', post_path(@post), method: :delete, data: {confim: 'DO YOU WANT DELETE POST?'} %>

app/views/posts/index.html.erb
<h1>INDEX ACTIONS</h1>
<%@posts.each do |post|%>
<article class="post">

  <section class="post-head">
   <!-- <%= image_tag post.image.url(:thumb), class: 'img-thumbnail thumb' if post.image? %>-->
    <h2> <%= link_to post.title, post_path(post)%> </h2>
   </section>

  <small>
    <time>
    <%= post.created_at.to_date.strftime("%d %B, %Y") %>
    </time>
    <% if logged_in? %>
  <%= link_to 'EDIT', edit_post_path(post), class: 'btn btn-warning btn-xs' %>
  <%= link_to 'Delete', posts_path(post), method: :delete, data: {confirm: "DELETE??"},
                                                          class: 'btn btn-danger btn-xs'%>
        <% end %>
  </small>

 </article>
<% end %>
<%= will_paginate @posts,  renderer: BootstrapPagination::Rails %>

app/views/posts/new.html.erb
<h1>NEW POST</h1>

<%= render 'form' %>

app/views/posts/show.html.erb
<% provide(:title, '@post.title') %>
<h1><%= @post.title %></h1>
<%= image_tag @post.image.url(:big), class: 'img-show' if @post.image? %>
<%= @post.body %>

<%= link_to 'edit', edit_post_path(@post) %>

<div id="disqus_thread"></div>
<script>


    var disqus_config = function () {
    this.page.url = 'http://localhost.com<%= request.original_fullpath %>';  // Replace PAGE_URL with your page's canonical URL variable
    this.page.identifier = '<%= @post.id %>'; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
    };

    (function() { // DON'T EDIT BELOW THIS LINE
        var d = document, s = d.createElement('script');
        s.src = 'https://poster-2.disqus.com/embed.js';
        s.setAttribute('data-timestamp', +new Date());
        (d.head || d.body).appendChild(s);
    })();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>