config/routes.rb
Rails.application.routes.draw do
  resources :addposts
  get 'password_resets/new'

  get 'passwrod_resets/new'

  get 'passwrod_resets/edit'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'posts#index'
  resources :posts

  resources :users
  get '/singup', to: 'users#new'
  post '/singup', to: 'users#create'

  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  resources :password_resets, only: [:new, :create, :edit, :update]

  resources :contacts, only: [:new, :show, :create]
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewsBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'POSTeR', posts_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Offer post', new_addpost_path, class: 'nav-link' %></li>
        <% if logged_in? %>
            <li><%= link_to 'List offer posts', addpost_path, class: 'nav-link' %></li>
            <li><%= link_to 'Massage to admins', contact_path, class: 'nav-link' %></li>
            <li><%= link_to 'Log out', logout_path, method: :delete %></li>
            <li><%= link_to 'Profile', user_path(current_user) %></li>
            <% else %>
            <li><%= link_to 'Sing UP', singup_path%></li>
            <li><%= link_to 'Log in', login_path %></li>
            <% end %>
        <li><%= link_to 'Contact us', new_contact_path, class: 'nav-link' %></li>

      </ul>
    </div>

  </div>
</div>


    <div class="col-md-12">
      <% flash.each do |name, msg| %>
      <div class="alert alert-<%= name %>">
        <%= msg %>
        <% end %>
      </div>
    </div>
<div class="container">
<%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
</body>
  </html>

app/views/layouts/users.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %></title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top" >
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'POSTeR', posts_path, class: 'navbar-brand' %>
    </div>
    <div class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Sing UP', singup_path%></li>
        <li><%= link_to 'CREATE NEW POST', new_post_path, class: 'nav-link' %></li>
        <li><a href="#">CONTACT US</a></li>

      </ul>
    </div>

  </div>
</div>




<div class="container">
  <div class="row">
    <div class="col-md-12">
      <% flash.each do |name, msg| %>
          <div class="alert alert-<%= name %>">
            <%= msg %>
      <% end %>
      </div>
    </div>
  </div>

  <%= yield %>
</div>

<%= debug(params) if Rails.env.development? %>
</body>
</html>